CREATE TABLE CONTRACTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (
    START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807  CYCLE) PRIMARY KEY,
        CONTRACT_TYPE NUMBER(2,0) NOT NULL,
    CONTRACT VARCHAR2(21) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    IBAN NUMBER(13,0),
    RISK_AMOUNT NUMBER(15,2),
    LIMIT_AMOUNT NUMBER(15,2),
    PENDING_AMOUNT NUMBER(15,2),
    FAILED_AMOUNT NUMBER(15,2),
    IS_ACTIVE NUMBER(1) DEFAULT 0 NOT NULL CHECK(IS_ACTIVE IN (0,1)),
    IS_DELIQUENCY  NUMBER(1) DEFAULT 0 NOT NULL CHECK(IS_DELIQUENCY IN (0,1)),

    MAXIMUM_COMISSION_AMOUNT NUMBER(15,2),
    MAXIMUM_REVOLVING_TAE NUMBER(15,2),
    MAXIMUM_REVOLVING_TIN NUMBER(15,2),

    PAYMENT_DUE_DATE DATE,
    PAYMENT_METHOD VARCHAR2(3),
    PAYMENT_MODALITY VARCHAR2(18),
    PERCENTAGE_TIN NUMBER(5,3)
);
CREATE TABLE RISKS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (
    START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807  CYCLE) PRIMARY KEY,
    NUMBER_PERSON NUMBER NOT NULL,
    LAST_SCORING NUMBER(10),
    LAST_REEVALUATED_DATE DATE,
    MAXIMUM_OUTSTANDING_AMOUNT NUMBER(15,2),
    MAXIMUM_OUTSTANDING_NUMBER NUMBER(10)
);
CREATE TABLE FINANCIABILITY (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (
    START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807  CYCLE) PRIMARY KEY,
    NUMBER_PERSON NUMBER NOT NULL,
    LOAD_DATE DATE NOT NULL,
    SEGMENTATION VARCHAR(1) NOT NULL,
    IS_CLIENT NUMBER(1) DEFAULT 0 NOT NULL CHECK(IS_CLIENT IN (0,1))
);

CREATE TABLE PERSON (
                       ID NUMBER GENERATED ALWAYS AS IDENTITY (
                           START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807  CYCLE) PRIMARY KEY,
                       NUMBER_PERSON NUMBER NOT NULL,
                       NAME VARCHAR2(50 CHAR),
                       CREATION_DATE DATE
);
CREATE TABLE PHYSIC_PERSON (
                        ID NUMBER PRIMARY KEY,
                        SURNAME VARCHAR2(50 CHAR),
                        BIRTH_DATE DATE,
                        CITY VARCHAR2(20 CHAR)
);
CREATE TABLE LEGAL_PERSON (
                               ID NUMBER PRIMARY KEY,
                               SOCIAL_NAME VARCHAR2(50 CHAR),
                               CONSTITUTION_DATE DATE,
                               CNAE VARCHAR2(8 CHAR)
);